+version: '3.8'

services:
  gorest:
    image: sgadwe/gorestdatadriventest:1.0
    volumes:
      - ./results:/app/results

  booking:
    image: sgadwe/mybookingapi:1.0
    volumes:
      - ./results:/app/results
      